### ISSUE TITLE
compatibility with onrobot gripper 2FG7

### ISSUE THREAD

**Issue by imlaras** [Osaka-University-Harada-Laboratory/onrobot#1]
Hello, this is not an issue but a question. Would this software be compatible with the onrobot gripper model 2FG7?

**Comment by takuya-ki** [comment]
@imlaras Thank you for your contact!
To be honest, I am not sure because the model was not tested with this.
I recommend that you first check if you can simply control the gripper via an onrobot compute box with Modbus TCP while referring to another repository [onrobot-rg](https://github.com/takuya-ki/onrobot-rg).

**Comment by imlaras** [comment]
Hi @takuya-ki thank you so much for your earlier responde! I do not have an onrobot compute box to check it out. Have you been capable of controlling it directly through the robot's TCP connector? Or do you always (with and without ros) need a compute box to communicate to the gripper?

**Comment by takuya-ki** [comment]
@imlaras Sorry to confuse you. The below repositories were developed for the gripper with a tool changer connecting to a compute box with an ethernet cable.
In README, I have added the description of the hardware configuration that I assume.

**Comment by imlaras** [comment]
Thank you!
